# Generated by Django 3.2.5 on 2021-11-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='progress',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
            preserve_default=False,
        ),
    ]
