# Generated by Django 3.2.5 on 2021-10-04 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profession', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_job', models.CharField(default='NA', max_length=50)),
                ('prof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profession.profession')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocks', models.IntegerField(default=100)),
                ('mutual_funds', models.IntegerField(default=100)),
                ('fds', models.IntegerField(default=100)),
                ('gold', models.IntegerField(default=100)),
                ('loans', models.IntegerField(default=100)),
                ('balance', models.IntegerField(default=100)),
                ('prtf_name', models.CharField(max_length=30)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
