# Generated by Django 3.2.5 on 2021-10-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='pg_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='total_prtf_val',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
