# Generated by Django 3.2.9 on 2021-11-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_portfolio_total_prtf_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='fds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='loans',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='mutual_funds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='stocks',
            field=models.IntegerField(default=0),
        ),
    ]
