# Generated by Django 3.2.9 on 2021-11-02 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211102_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='prtf_name',
        ),
    ]
